Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -37,8 +37,10 @@ jobs:
       
     - name: Run the tests
       run: | 
-        npx hardhat test # Check if tests passed
-        if [ $? -ne 0 ]; 
-          then echo "Tests failed" exit 1
-          else echo "All tests passed" 
+        npx hardhat test
+        if [ $? -ne 0 ]; then
+          echo "Tests failed"
+          exit 1
+        else
+          echo "All tests passed" 
         fi
