Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -36,4 +36,9 @@ jobs:
       run: npx hardhat compile
       
     - name: Run the tests
-      run: | npx hardhat test # Check if tests passed if [ $? -ne 0 ]; then echo "Tests failed" exit 1 else echo "All tests passed" fi
+      run: | 
+        npx hardhat test # Check if tests passed
+        if [ $? -ne 0 ]; 
+          then echo "Tests failed" exit 1
+          else echo "All tests passed" 
+        fi
